### ISSUE TITLE
WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

### ISSUE THREAD

**Issue by PSSOMgdelb6** [bpennypacker/WeatherFlow-Indigo-Plugin#17]
`WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 681, in runConcurrentThread
  File "plugin.py", line 622, in _process_message
  File "plugin.py", line 827, in process_obs_tempest
  File "plugin.py", line 124, in degrees_to_cardinal
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

   WeatherFlow Smart Weather Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)`

Indigo 7.4
WF 0.2.1
Tempest

**Comment by bpennypacker** [comment]
This, and I believe your other issue, should both be fixed in v0.2.2 that I just released. Please give it a try.

**Comment by PSSOMgdelb6** [comment]
This is what I got upon 0.2.2 install

![0 2 2 Errors](https://user-images.githubusercontent.com/68129529/87481452-39228380-c5e4-11ea-962d-49fd99c2debb.png)

**Comment by PSSOMgdelb6** [comment]
0.2.3 no WS or UDP errors. Thanks!
