### ISSUE TITLE
Net Cat

### ISSUE THREAD

**Issue by PSSOMgdelb6** [bpennypacker/WeatherFlow-Indigo-Plugin#19]
Your instructions state to run a terminal command to verify traffic.

The Mac Firewall now has 'NC' -Allow incoming connections.

Was this needed only for the test, and we can now delete/block? or does the plugin need allow to work?

**Comment by bpennypacker** [comment]
It's needed. The `nc` command has basically just told the Mac that you need to allow port 50222 traffic in so that the plug-in can listen for it. If you remove the `nc` entry then the plug-in will no longer be able to receive broadcasts from your hub.
