### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by PSSOMgdelb6** [bpennypacker/WeatherFlow-Indigo-Plugin#20]
Thanks for the plugin! Will future versions include:

1) Decimal format options  80º,  80.2º, 80.25º for UI Control Pages?
2) Capturing the FORECAST data that the WF app displays, so we can use it in Indigo?

**Comment by bpennypacker** [comment]
1. Being considered for a future release
2. See [this documentation](https://github.com/bpennypacker/WeatherFlow-Indigo-Plugin/wiki/Websocket-summary-data) for details on this. I did receive an email from another user who said they had been in contact with the WeatherFlow team, and that official support for forecast data, etc. would be coming soon. If/when that happens I do plan to start supporting it in the plug-in.
