### ISSUE TITLE
Reloading plugin "WeatherFlow Smart Weather 0.2.1"

### ISSUE THREAD

**Issue by PSSOMgdelb6** [bpennypacker/WeatherFlow-Indigo-Plugin#21]
Plugin has stopped getting data from Tempest. I reloaded the plugin to try and wake it up. Every device has an error.

![547pm ReLoadError](https://user-images.githubusercontent.com/68129529/87232947-e6449400-c377-11ea-9a8b-bbc6dfb1c3fd.png)

**Comment by PSSOMgdelb6** [comment]
0.2.3 no WS or UDP errors. Thanks!

**Comment by bpennypacker** [comment]
Awesome, thanks for the update!
