### ISSUE TITLE
WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread

### ISSUE THREAD

**Issue by achterberg** [bpennypacker/WeatherFlow-Indigo-Plugin#24]
WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 681, in runConcurrentThread
  File "plugin.py", line 622, in _process_message
  File "plugin.py", line 845, in process_obs_tempest
IndexError: list index out of range

   WeatherFlow Smart Weather Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

Indigo 7.4
WF 0.2.2

**Comment by bpennypacker** [comment]
Are you using the plugin via UDP or Websockets? If you're using the Websocket version then what is the Station ID of the station you are using?

**Comment by achterberg** [comment]
I actually have both set up as different devices. My station ID for websockets is 18541

**Comment by bpennypacker** [comment]
Give v0.2.3 a try. If that's still throwing exceptions like these I may need to break down and purchase a Tempest for myself so I can get real UDP messages from one in order to troubleshoot...

**Comment by achterberg** [comment]
Installed and so far no errors. Thanks.

**Comment by PSSOMgdelb6** [comment]
0.2.3 no WS or UDP errors. Thanks!

**Comment by bpennypacker** [comment]
Awesome, thanks for the update!
