### ISSUE TITLE
Rain Accum

### ISSUE THREAD

**Issue by jltnol** [bpennypacker/WeatherFlow-Indigo-Plugin#27]
Not sure this is the place for this... I'm not too familiar with Github protocol, so forgive me if I'm making a mess.

Let me stay from the outset your plugin is wonderful!  I had the Tempest setup with the hub, and got the plugin linked to the hub in less than 10 minutes. The Wiki was super easy to understand, not overly technical, and very easy to follow.  I can now track all that data in Indigo, a good thing.  

I am curious about rain accumulation.  I did write to the Weatherflow folks who said that rain accumulation data was stored in the hub, so I'm assuming it is available for harvesting by the plugin.  I don't pretend to understand how easy or hard that might be to implement, but that would be something I'd love to track, and I'm sure others probably would as well.

Even without that data, the plugin is GREAT!

**Comment by bpennypacker** [comment]
The devices in the plugin only expose the public data that the WeatherFlow folks document in their API (and explicitly state s for public consumption). They also provide slightly different information based on whether you're using a UDP plugin that only provides the local raw data collected by your Tempest/Sky/Air device, or the Websocket plugin, which provides curated data from WeatherFlow servers based on readings your Tempest/Sky/Air devices sends to them. Rain accumulation should be included in the Websocket data.

Did you email them directly or did you post a question on their web forum? If you posted to their forum could you provide a link to the discussion there?

**Comment by jltnol** [comment]
For the moment, I'm tracking rain accumulation from the web socket side of things which is ok. Better than nothing, but would still rather have that data from my Tempest.    When I go to the tempest webpage for my device, (the mostly blue page...) I see there is a listing for **Rain(Today) and Rain(Yesterday)**.  That data is also available on the iOS app for Tempest too.

However I absolutely understand that rain accumulation data may not be available via the API, even though it's available on the web page.

I did write directly to Tempest and got the following response from "William Gidley(WeatherFlow Support)"

_Thanks for writing in. All data is stored on the station Hub - Tempest can store about 1 hour worth of data on-board the device, but that is only used if it can't send the data to the Hub (such as during a power outage).  I'm not sure why the 3rd party software that you're using doesn't show it - you can view our API documentation and see that it's listed under the UDP broadcasts (no internet connection needed, so no data from the cloud) and under the REST api (internet connection needed, data comes from the cloud). 

Link to the API: https://weatherflow.github.io/SmartWeather/_

So while I almost understand how all this works, and understand that just because the Tempest device tracks Rain accumulation to display the webpage, that it may not really, REALLY be available to harvest via the API.    I guess I was halfway thinking the API had been updated to include this info after you worked on your plugin, so was hoping an update might be able to include it.

And I suppose I could try to glean this information from the "raw_obs" data as well.

**Comment by jltnol** [comment]
So I've actually had both the Websocket and the UDP device in Indigo from Day 1.  Our rainfall has been almost non-existent, but today, we had shower.  The webpage for my station [show](https://tempestwx.com/station/27327/grid) that I've and .38" of rain today, which is probably right. This is the data I'm trying to get into indigo, but it doesn't show up in either the UDP or the Websocket Device.  

I've recently noticed that the plugin has created a folder of variables, including one called "87843_precip_accum_local_yesterday", but am not sure what that number actually is, or if/when it is updated. I would assume that it is what it says... total rainfall from yesterday. But we didn't have any rainfall yesterday, much less the 5.xxxx number it shows.  

What I'm really hoping for is a way to get the "Rain Today" information from the Tempest device that shows up on the webpage into Indigo in real time, but just don't see how that is supposed to happen.

**Comment by bpennypacker** [comment]
> I've recently noticed that the plugin has created a folder of variables, including one called "87843_precip_accum_local_yesterday", but am not sure what that number actually is,

That's documented [here](https://github.com/bpennypacker/WeatherFlow-Indigo-Plugin/wiki/Websocket-summary-data). That is basically data that the WeatherFlow team says isn't actually publicly supported and may change or be removed in the future, so I didn't want to directly support it as properties in the plugin. In a nutshell, any of this summary data that is seen in an event is exposed as those variables.

The best thing you can probably do is enable debugging in the plug-in for a while when it's raining and see if you can identify where/how the rain is being reported. I'll try to do this myself the next time we have rain here (hopefully next Monday).

**Comment by jltnol** [comment]
So here’s what I know, which I freely admit isn’t much. My webpage is showing a total of .09” of Rain (Today). The way I think that the Tempest delivers its observations is via Metric, so I changed the settings for the webpage for Rain to mm, and so now my webpage reads 2.3mm of Rain(Today).

In looking at the variables automatically created in Indigo by the plugin, I see nothing that resembles 2.3mm, .23cm, or even .09”..  And the same for both the UDP and Websocket Indigo devices. None of those digits shows up anywhere. In all cases, ZERO sees to be the data in any and all of the places that holds data for precipitation.  (The rain was earlier this afternoon, its now after 10PM)

So I put the plugin into debug mode, took a sample of that data from the Indigo log, and grabbed data from one observation all the way to the next observation. I put that data into a document, searched for 2.3, .23 and .09, and none of those numbers show up in the debug data. 

So to me that means that the Rain(Today) data that I see on the web page is either not available to the plugin, or the plugin isn’t setup to gather that data. 

If that data isn’t available to the plugin, I’m hoping a firmware upgrade for the Tempest one day might allow Rain Today data to be gathered, but it just doesn’t seem possible now.

Please don’t misunderstand my post here. I’m happy with the Tempest and even more happy with your plugin, which just makes everything soooo much better.  While I’d like to have this data, not having it is far from the end of the world.  Please keep up the great work, and I look forward to one day hopefully gathering that data into Indigo.

**Comment by bpennypacker** [comment]
Thanks for the update. I'm still hoping to do some debugging of this in the next day or two when we get some rain. Probably the best thing you could do in the meantime would be to bring this issue up in the developers section of their [community forum](https://community.weatherflow.com/). The more publicity about things like this the more likely they are to respond.

**Comment by jltnol** [comment]
Done



JT

**Comment by jltnol** [comment]
Hey htere

So this is the response I got:

	peter <https://community.weatherflow.com/u/peter> SWS Field Testers 
September 30
Total daily rain accumulation is available via the REST API and Websocket. If the Indigo plugin uses those data sources (rather than the local UDP broadcasts where it is not available), then it is the plugin that has chosen not to display it.

**Comment by bpennypacker** [comment]
So I just did a bit of debugging by locating a rain front on the radar at weather.com then using the [WeatherFlow station map](https://tempestwx.com/map) to find stations that were currently reporting rain and used that to test the plugin. From what I can see everything is being reported properly. The WeatherFlow website showed the station I was monitoring was reporting 0.13" of rain, which is approximately 3.3 mm. Both the debug log from the plugin and the device details in Indigo showed the `rain_accumulated_final` field (Rain Accumulated Final) shows `3.297971` which rounds up to 3.3 mm. As it was raining I also saw the value of the `precipitation` field (Precipitation Accumulated) change over time.

**Comment by jltnol** [comment]
Curious

I thought I had looked at all those and none of them seem to indicate the amount of rain the website did.

Not sure when you’ll get this, but do the numbers go DOWN after the rain has passed for a few days ? 

Also wondering if there is a firmware difference.  My Tempest is Firmware Revision 143.


No rain, so can’t check. : (.  My go squirt the hose on it for a bit to see if I can get it to measure something..

Thanks

 Jeffrey

**Comment by bpennypacker** [comment]
Interesting. The device I was testing with is station ID 27081, and it's showing firmware revision 134 in its observations. If you configure the plug-in to use that station ID & enable debugging you should be able to confirm that for yourself.

My understanding is that rain_accumulated_final provides the total rainfall since midnight local time, so it should reset to 0 each night at midnight.

**Comment by jltnol** [comment]
Hey Bruce

Almost a step ahead of you.  Just today, we had some rain, but still nothing showing up in the data point you mention. So I actually did the same thing you did, substituted a different station ID into the plugin, and PRESTO… there is a rain amount in the field you’ve mentioned.

As luck would have it, my UDP device stopped updating in Indigo on Monday, even tho the iOS app, the web page, and the Websocket device in Indigo were all updating.  I tried a few things, none of which worked, but created a new UDP device, and it started updating right away.


With that in mind, and based on the fact that the one other station I tired was reporting rain, I also created a new Websocket device in Indigo, and again… there was my rain total from today.  Have no idea why the UDP device stopped updating in Indigo, and no idea why the 1st Websocket device wasn’t reporting rain, but the 2nd one did, so at least I got that far…

If there are any logs I can send you if you’d like to look into this a bit more, let me know.  And I did check my firmware, and its the same… 134.

One thing  is both my original UDP and Websocket device had “State Display” as ‘blank’.  I’ve actually chosen one of the data points as the “State Display”, so don’t know if that has any impact on anything. 


Thank you so much for following up with me.   I’ve been waiting for some rain, and today was the day.  And once I had rain totals from a different station in Indigo, I knew something else was wrong, and started on my trek. For now, I’m happy!

Cheers

 Jeffrey

**Comment by bpennypacker** [comment]
Could you let me know what your station ID is? I'd like to monitor it for a bit to see if I can spot anything.

**Comment by jltnol** [comment]
Hey Bruce

I’m guessing this the last digits of this URL:
https://tempestwx.com/station/27327/ <https://tempestwx.com/station/27327/>



Jeffrey

**Comment by jltnol** [comment]
So I think I’ve had success.

It’s been a long dry stretch, but we’ve had significant rain today, and it appears as if the plug in is registering the appropriate rainfall in mm. 

From indigo, that value goes into a variable, and then with some plain python math, I convert mm to inches, put it in a 2nd variable, track rain for today, yesterday this week, and this month, and get a nice bar graph like below. 


So, once again…. THANK YOU so much for helping me get to this point. 


Regards

 Jeffrey


.
