### ISSUE TITLE
Fix exception handler

### ISSUE THREAD

**Issue by boisy** [bpennypacker/WeatherFlow-Indigo-Plugin#28]
Hi Bruce,

Line 546 in your WeatherFlow plugin.py:

Change:

`except:`

to:

`except Exception as e:`

to prevent an error in the Indigo logs.

**Comment by bpennypacker** [comment]
Thanks! I'll look into this as soon as I get a chance.

**Comment by bpennypacker** [comment]
Fixed in the v0.3.0 release
