### ISSUE TITLE
Device not updating

### ISSUE THREAD

**Issue by boisy** [bpennypacker/WeatherFlow-Indigo-Plugin#29]
I have two devices I created under the WeatherFlow plug-in: Humidity and Temperature. Using either the web socket or UDP, I'm noticing that the temperature does not get updated in a timely fashion. It can go days without updating

Attached are images of both the debug output of the plugin that clearly shows the obs_st data (with temperature at 13.7C) and the other screenshot showing the device's last update time in the early morning today.

![Screen Shot 2020-12-13 at 7 17 13 PM](https://user-images.githubusercontent.com/719845/102030326-fa9e1a00-3d77-11eb-9355-510fc04d53d2.png)
![Screen Shot 2020-12-13 at 7 17 37 PM](https://user-images.githubusercontent.com/719845/102030329-fc67dd80-3d77-11eb-8fc7-188011e1f7e2.png)

**Comment by bpennypacker** [comment]
1. If you go to the Device Settings in Indigo, what do you have selected for "State display"?
2. If you click on the device and look at the Custom States that appear below it (see the below screenshot) does that show the properties updating properly?
3. What is the Station ID for your device? 

![Screen Shot 2020-12-15 at 11 04 27 AM](https://user-images.githubusercontent.com/2932316/102240123-85405f80-3ec5-11eb-9f10-adeb422daf85.jpeg)

**Comment by boisy** [comment]
Hi Bruce,

1. Here’s the state as of right now of the two devices (note the data of the humidity was yesterday):





2. Here are the custom states for both devices:

 



3. My station ID is here:



—
Boisy Gene Pitre
http://www.pitre.org

**Comment by boisy** [comment]
![Screen Shot 2020-12-13 at 7 17 13 PM](https://user-images.githubusercontent.com/719845/102945139-8a337f00-4482-11eb-816c-1b0c9f432b2c.png)
![Screen Shot 2020-12-13 at 7 17 37 PM](https://user-images.githubusercontent.com/719845/102945142-8acc1580-4482-11eb-912b-4fec26c34a59.png)
![Screen Shot 2020-12-17 at 3 47 11 PM](https://user-images.githubusercontent.com/719845/102945144-8acc1580-4482-11eb-90c3-ad259a0db751.png)

**Comment by boisy** [comment]
For some reason the images didn't get put inline with the first message. I just added them.

**Comment by boisy** [comment]
![Screen Shot 2020-12-22 at 6 23 51 PM](https://user-images.githubusercontent.com/719845/102945325-0a59e480-4483-11eb-8913-273f96fdcf6a.png)
![Screen Shot 2020-12-22 at 6 23 58 PM](https://user-images.githubusercontent.com/719845/102945328-0af27b00-4483-11eb-92f9-b7d9b0f7d2e0.png)
![Screen Shot 2020-12-22 at 6 24 27 PM](https://user-images.githubusercontent.com/719845/102945330-0b8b1180-4483-11eb-91f7-fb0c146aaabf.png)

**Comment by boisy** [comment]
![Screen Shot 2020-12-22 at 6 23 51 PM](https://user-images.githubusercontent.com/719845/102945355-1e054b00-4483-11eb-8029-b27e41cb7f7e.png)
![Screen Shot 2020-12-22 at 6 24 27 PM](https://user-images.githubusercontent.com/719845/102945356-1e9de180-4483-11eb-9402-9190d056fff3.png)
![Screen Shot 2020-12-22 at 6 25 02 PM](https://user-images.githubusercontent.com/719845/102945359-1e9de180-4483-11eb-9907-f21a370b4ccf.png)

**Comment by boisy** [comment]
For some reason the images didn't get pasted correctly into the earlier message. I just posted them now. Notice that the humidity hasn't been updated since December 14.

**Comment by boisy** [comment]
Hi Bruce,

I now have three devices (temperature, humidity, baron. pressure) all using Websockets. If I make a change to the temperature device, for example, then save it, then IT will update, but the other two won't. If I then make a change to the humidity device, then IT will update, but the other two won't. Only the last device to get updated (or created) seems to be processing the messages, leaving any other devices not updating.

**Comment by boisy** [comment]
Here's a type that your plug-in should handle.

![image](https://user-images.githubusercontent.com/719845/103724121-3dc76380-4f99-11eb-9f28-54708ee2bb64.png)

**Comment by bpennypacker** [comment]
> I now have three devices (temperature, humidity, baron. pressure) all using Websockets.

Why are you creating separate Indigo devices for the same WeatherFlow device? You should only be creating a single Indigo device and referring to the different states of that one device to obtain the data you are interested in. Running multiple Indigo devices for the same WeatherFlow device is likely the reason for the problems you are encountering.

FYI, I just released v0.3.0 of the plug-in, which adds a new mode state that tracks the evt_device_offline and evt_device_online events from WeatherFlow and also fixes the exception that you reported in #28.

**Comment by boisy** [comment]
I thought a separate device was needed for each weather property. I see now that the single device has all of the info in state. Thanks for clarifying. You can close this issue.

**Comment by bpennypacker** [comment]
Sounds good. Please let me know if you do encounter any other issues.
