### ISSUE TITLE
Upgraded to v0.1.0 Error:

### ISSUE THREAD

**Issue by Koreysherwin** [bpennypacker/WeatherFlow-Indigo-Plugin#6]
Loops over and over:

May 28, 2020 at 2:19:24 PM
   Stopping plugin WeatherFlow Smart Weather (pid 21167)
   WeatherFlow Smart Weather Error exception in deviceStopComm(WF Tempest 1): 'ST-00002899-SmartWeatherTempestUDP'
   Stopped plugin WeatherFlow Smart Weather
   Upgrading plugin WeatherFlow Smart Weather to newer version 0.1.0 (previous version moved to trash)
   Loading plugin "WeatherFlow Smart Weather 0.1.0"
   Starting plugin "WeatherFlow Smart Weather 0.1.0" (pid 65139)
   Started plugin "WeatherFlow Smart Weather 0.1.0"
   WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 671, in runConcurrentThread
  File "plugin.py", line 592, in _process_message
  File "plugin.py", line 937, in process_rapid_wind
KeyError: 'key windspeed not found in dict'

   WeatherFlow Smart Weather Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
   WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 671, in runConcurrentThread
  File "plugin.py", line 592, in _process_message
  File "plugin.py", line 937, in process_rapid_wind
KeyError: 'key windspeed not found in dict'

   WeatherFlow Smart Weather Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
   Reloading plugin "WeatherFlow Smart Weather 0.1.0"
   Stopping plugin "WeatherFlow Smart Weather 0.1.0" (pid 65139)
   WeatherFlow Smart Weather Error exception in deviceStopComm(WF Tempest 1): 'ST-00002899-SmartWeatherTempestUDP'
   Stopped plugin "WeatherFlow Smart Weather 0.1.0"
   Starting plugin "WeatherFlow Smart Weather 0.1.0" (pid 65193)
   Started plugin "WeatherFlow Smart Weather 0.1.0"
   WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 671, in runConcurrentThread
  File "plugin.py", line 592, in _process_message
  File "plugin.py", line 937, in process_rapid_wind
KeyError: 'key windspeed not found in dict'

   WeatherFlow Smart Weather Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
   WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 671, in runConcurrentThread
  File "plugin.py", line 592, in _process_message
  File "plugin.py", line 937, in process_rapid_wind
KeyError: 'key windspeed not found in dict'

   WeatherFlow Smart Weather Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
   WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):

**Comment by Koreysherwin** [comment]
Debugger enabled:
 WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 671, in runConcurrentThread
  File "plugin.py", line 592, in _process_message
  File "plugin.py", line 943, in process_rapid_wind
KeyError: 'obs'

   WeatherFlow Smart Weather Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00011201",
    "ob": [
        1590701139,
        1.83,
        321
    ],
    "serial_number": "SK-00014582",
    "type": "rapid_wind"
}
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00016456",
    "ob": [
        1590701137,
        4.6,
        24
    ],
    "serial_number": "ST-00002899",
    "type": "rapid_wind"
}
   WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 671, in runConcurrentThread
  File "plugin.py", line 592, in _process_message
  File "plugin.py", line 943, in process_rapid_wind
KeyError: 'obs'

   WeatherFlow Smart Weather Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

**Comment by bpennypacker** [comment]
Try v0.1.1 that I just published.

**Comment by Koreysherwin** [comment]
Getting a new error with 0.1.1:

 Upgrading plugin WeatherFlow Smart Weather to newer version 0.1.1 (previous version moved to trash)
   Loading plugin "WeatherFlow Smart Weather 0.1.1"
   Starting plugin "WeatherFlow Smart Weather 0.1.1" (pid 31741)
   Started plugin "WeatherFlow Smart Weather 0.1.1"
   WeatherFlow Smart Weather Debug startup called
   WeatherFlow Smart Weather Debug deviceStartComm(WF AIR)
   WeatherFlow Smart Weather Debug deviceStartComm(WF SKY)
   WeatherFlow Smart Weather Debug deviceStartComm(WF Tempest)
   WeatherFlow Smart Weather Debug deviceStartComm(WF Wind Rapid)
   WeatherFlow Smart Weather Debug Starting UDP listener loop on port 50222
   WeatherFlow Smart Weather Debug added device serial number SK-00014582
   WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 671, in runConcurrentThread
  File "plugin.py", line 592, in _process_message
  File "plugin.py", line 932, in process_rapid_wind
KeyError: 'obs'

   WeatherFlow Smart Weather Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00011201",
    "ob": [
        1590763916,
        0.0,
        0
    ],
    "serial_number": "SK-00014582",
    "type": "rapid_wind"
}
   WeatherFlow Smart Weather Debug added device serial number ST-00002899
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00016456",
    "ob": [
        1590763911,
        1.61,
        355
    ],
    "serial_number": "ST-00002899",
    "type": "rapid_wind"
}
   WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 671, in runConcurrentThread
  File "plugin.py", line 592, in _process_message
  File "plugin.py", line 932, in process_rapid_wind
KeyError: 'obs'

   WeatherFlow Smart Weather Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00011201",
    "ob": [
        1590763919,
        0.94,
        250
    ],
    "serial_number": "SK-00014582",
    "type": "rapid_wind"
}
   WeatherFlow Smart Weather Debug added device serial number HB-00016456
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00016456",
    "ob": [
        1590763914,
        0.45,
        334
    ],
    "serial_number": "ST-00002899",
    "type": "rapid_wind"

—

**Comment by bpennypacker** [comment]
Give v0.1.2 a try

**Comment by Koreysherwin** [comment]
May 29, 2020 at 10:19:31 AM
   Upgrading plugin WeatherFlow Smart Weather to newer version 0.1.2 (previous version moved to trash)
   Loading plugin "WeatherFlow Smart Weather 0.1.2"
   Starting plugin "WeatherFlow Smart Weather 0.1.2" (pid 55687)
   Started plugin "WeatherFlow Smart Weather 0.1.2"
   WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 672, in runConcurrentThread
  File "plugin.py", line 587, in _process_message
  File "plugin.py", line 901, in process_obs_air
IndexError: list index out of range

   WeatherFlow Smart Weather Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

May 29, 2020 at 10:20:34 AM
   WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 672, in runConcurrentThread
  File "plugin.py", line 587, in _process_message
  File "plugin.py", line 901, in process_obs_air
IndexError: list index out of range

   WeatherFlow Smart Weather Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

**Comment by bpennypacker** [comment]
v0.1.3 should fix that one.

**Comment by Koreysherwin** [comment]
Yes!

All working as it should Thanks Bruce!!


If you get bored, how about being able to select what is displayed in the state field in Indigo?

IE: Temp or Wind or..







Thanks again!
—
Korey Sherwin
SherwinSound.com
702-239-1195

**Comment by bpennypacker** [comment]
Awesome, glad to hear it's working now!

Customizing the state field sounds like an interesting idea. I'll see what I can do.
