### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by jrickmd** [bpennypacker/WeatherFlow-Indigo-Plugin#7]
Loading 0.1.0 get error message:

'
   Started plugin "WeatherFlow Smart Weather 0.1.0"
   WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 671, in runConcurrentThread
  File "plugin.py", line 612, in _process_message
  File "plugin.py", line 785, in process_obs_tempest
KeyError: 'key temp not found in dict'

   WeatherFlow Smart Weather Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
'

and doesn't load. This happens after multiple attempts to  reload.

Rick

**Comment by bpennypacker** [comment]
Interesting. That particular line of code is trying to read one of the new properties from the config dialog. It's almost as if Indigo didn't actually update what it sees in the plugin based on the new properties in the PluginConfig.xml file. I guess Indigo doesn't initialize the new values unless/until you actually go into the plugin configuration dialog. I'll have to modify the code to account for this...

**Comment by bpennypacker** [comment]
Try v0.1.1 that I just published.

**Comment by Koreysherwin** [comment]
Getting a new error with 0.1.1

 Upgrading plugin WeatherFlow Smart Weather to newer version 0.1.1 (previous version moved to trash)
   Loading plugin "WeatherFlow Smart Weather 0.1.1"
   Starting plugin "WeatherFlow Smart Weather 0.1.1" (pid 31741)
   Started plugin "WeatherFlow Smart Weather 0.1.1"
   WeatherFlow Smart Weather Debug startup called
   WeatherFlow Smart Weather Debug deviceStartComm(WF AIR)
   WeatherFlow Smart Weather Debug deviceStartComm(WF SKY)
   WeatherFlow Smart Weather Debug deviceStartComm(WF Tempest)
   WeatherFlow Smart Weather Debug deviceStartComm(WF Wind Rapid)
   WeatherFlow Smart Weather Debug Starting UDP listener loop on port 50222
   WeatherFlow Smart Weather Debug added device serial number SK-00014582
   WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 671, in runConcurrentThread
  File "plugin.py", line 592, in _process_message
  File "plugin.py", line 932, in process_rapid_wind
KeyError: 'obs'

   WeatherFlow Smart Weather Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00011201",
    "ob": [
        1590763916,
        0.0,
        0
    ],
    "serial_number": "SK-00014582",
    "type": "rapid_wind"
}
   WeatherFlow Smart Weather Debug added device serial number ST-00002899
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00016456",
    "ob": [
        1590763911,
        1.61,
        355
    ],
    "serial_number": "ST-00002899",
    "type": "rapid_wind"
}
   WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 671, in runConcurrentThread
  File "plugin.py", line 592, in _process_message
  File "plugin.py", line 932, in process_rapid_wind
KeyError: 'obs'

   WeatherFlow Smart Weather Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00011201",
    "ob": [
        1590763919,
        0.94,
        250
    ],
    "serial_number": "SK-00014582",
    "type": "rapid_wind"
}
   WeatherFlow Smart Weather Debug added device serial number HB-00016456
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00016456",
    "ob": [
        1590763914,
        0.45,
        334
    ],
    "serial_number": "ST-00002899",
    "type": "rapid_wind"

—
Korey Sherwin
SherwinSound.com
702-239-1195

**Comment by bpennypacker** [comment]
Should all be fixed as part of #6
